apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapideployment
spec:
  selector:
    matchLabels:
      app: restapi
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
      - image: msudan21/msrepo:restapi
        name: restapi
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
      restartPolicy: Always
      imagePullSecrets:
      - name: dockerhubsecret
